      PROGRAM BRUTEPRIMES

C *** COMPUTE ALL PRIMES UP TO RMC USING A RATHER UNELEGANT 
C *** BUT STRAIGHTFORWARD METHOD

      REAL NUMBER
      OPEN (UNIT=1,FILE='primes.out',STATUS='UNKNOWN')
 
      WRITE(*,*)"ENTER UPPER LIMIT"
      READ(*,*)RMC

      DO 14 NUMBER=1.,RMC

      DO 21 DENOMI=2.,NUMBER-1.
      IF( INT(NUMBER/DENOMI)-(NUMBER/DENOMI) .EQ. 0.)GOTO 14
   21 CONTINUE
      
      WRITE(*,*)INT(NUMBER)

   14 CONTINUE

      STOP 
      END


